CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`age` int NOT NULL,
	`state` varchar(2) NOT NULL,
	`zipCode` varchar(10) NOT NULL,
	`vehicleType` varchar(100) NOT NULL,
	`vehicleYear` int NOT NULL,
	`hasRecentAccidents` enum('yes','no') NOT NULL,
	`currentInsurer` varchar(200) NOT NULL,
	`coverageType` varchar(100) NOT NULL,
	`ownershipStatus` enum('financed','owned','leased') NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`ipAddress` varchar(45),
	`userAgent` text,
	`referrer` text,
	`utmSource` varchar(200),
	`utmMedium` varchar(200),
	`utmCampaign` varchar(200),
	`status` enum('new','sent','failed') NOT NULL DEFAULT 'new',
	`sentToNetwork` varchar(200),
	`sentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
